apiVersion: v1
kind: Service
metadata:
  name: event-bus-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: evern-bus
  ports:
  - name: event-bus
    protocol: TCP
    port: 4005
    targetPort: 4005
